[app]
# Enable or disable user registration
enable_registration = true

[logging]
# Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
log_level = ERROR

# Maximum size of log file before rotation (in bytes)
log_file_max_bytes = 10485760

# Number of backup log files to keep
log_file_backup_count = 5

# Enable or disable console logging
log_enable_console = true

# Enable or disable file logging
log_enable_file = true